<#
.SYNOPSIS
    Runs Windows App Certification Kit (WACK) validation for Store submission.

.DESCRIPTION
    Automates the WACK test process for the latest available appx/msix package.
    1. Finds the latest MSIX bundle in AppPackages.
    2. Executes WACK test (appcert.exe) with "Store App" profile.
    3. Analyzes the XML report and summarizes results.

.PARAMETER TestProfile
    XML profile path for WACK. Defaults to a standard Store App profile.

.PARAMETER OutputDir
    Directory to save WACK reports. Defaults to `scripts\wack_reports`.
#>

param(
    [string]$TestProfile,
    [string]$OutputDir
)

# --- 0. Check for Administrator Privileges ---
$currentPrincipal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "WACK requires Administrator privileges." -ForegroundColor Yellow
    Write-Host "Relaunching as Administrator..." -ForegroundColor Cyan

    # Re-run this script as Admin. -NoExit keeps the window open so results can be read.
    $argsList = "-NoProfile -ExecutionPolicy Bypass -NoExit -File `"$($MyInvocation.MyCommand.Path)`""
    if ($TestProfile) { $argsList += " -TestProfile `"$TestProfile`"" }
    if ($OutputDir) { $argsList += " -OutputDir `"$OutputDir`"" }

    Start-Process powershell -ArgumentList $argsList -Verb RunAs
    exit
}

$ErrorActionPreference = 'Stop'
$ScriptDir = $PSScriptRoot
$ProjectRoot = Split-Path -Parent $ScriptDir
$AppPackagesDir = Join-Path $ProjectRoot 'PhotoGeoExplorer\AppPackages'

# --- 1. Locate WACK Tool ---
$KitPath86 = "${env:ProgramFiles(x86)}\Windows Kits\10\App Certification Kit\appcert.exe"
$KitPath64 = "${env:ProgramFiles}\Windows Kits\10\App Certification Kit\appcert.exe"

if (Test-Path $KitPath64) { $AppCert = $KitPath64 }
elseif (Test-Path $KitPath86) { $AppCert = $KitPath86 }
else {
    throw "Windows App Certification Kit (appcert.exe) not found. Please install Windows SDK."
}

Write-Host "Using WACK: $AppCert" -ForegroundColor Gray

# --- 2. Locate Target Package ---
if (-not (Test-Path $AppPackagesDir)) { throw "AppPackages not found. Run Build first." }

# Priority 1: Find LocalDebug Signed MSIX (Created by DevInstall.ps1)
# WACK requires the package to be signed and trusted to install/test it.
# The 'Test' bundles generated by VS are often unsigned if 'AppxPackageSigningEnabled=false' was used.
$SignedPackages = Get-ChildItem -Path $AppPackagesDir -Recurse -Filter "PhotoGeoExplorer_LocalDebug.msix" |
                  Sort-Object LastWriteTime -Descending

if ($SignedPackages) {
    $TargetPackage = $SignedPackages | Select-Object -First 1
    Write-Host "Target (Signed Output): $($TargetPackage.Name)" -ForegroundColor Cyan
} else {
    # Priority 2: Fallback to Bundles (May fail if unsigned)
    Write-Warning "Signed LocalDebug package not found. Falling back to search for bundles."
    Write-Warning "WACK may fail if the bundle is unsigned."

    $Bundles = Get-ChildItem -Path $AppPackagesDir -Recurse -Include *.msixbundle, *.appxbundle |
               Sort-Object LastWriteTime -Descending
    $TargetPackage = $Bundles | Select-Object -First 1
}

if (-not $TargetPackage) { throw "No app package found in $AppPackagesDir." }

Write-Host "Path:   $($TargetPackage.FullName)" -ForegroundColor Gray

# --- 3. Prepare Output ---
if (-not $OutputDir) { $OutputDir = Join-Path $ScriptDir 'wack_reports' }
if (-not (Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$ReportXml = Join-Path $OutputDir "WACK-$Timestamp.xml"

# --- 4. Run WACK ---
Write-Host "`nStarting WACK Test... (This may take several minutes)" -ForegroundColor Yellow
Write-Host "Report will be saved to: $ReportXml" -ForegroundColor Gray

# Reset WACK state to clear any previous failures/pending tasks
Write-Host "Resetting WACK state..." -ForegroundColor Gray
Start-Process -FilePath $AppCert -ArgumentList "reset" -Wait

# Use "Store App" validation settings
# Note: WinUI 3 Desktop apps in MSIX are treated as Store apps.
$Args = @("test", "-apptype", "calt", "-packagepath", $TargetPackage.FullName, "-reportoutputpath", $ReportXml)

Write-Host "Executing command: $AppCert $Args" -ForegroundColor Gray
$Process = Start-Process -FilePath $AppCert -ArgumentList $Args -PassThru -Wait

if ($Process.ExitCode -ne 0) {
    Write-Warning "WACK exited with code $($Process.ExitCode). Check report for details."
} else {
    Write-Host "WACK execution completed." -ForegroundColor Green
}

# --- 5. Analyze Report ---
if (Test-Path $ReportXml) {
    Write-Host "`n--- Analysis Summary ---" -ForegroundColor Cyan
    [xml]$XmlContent = Get-Content $ReportXml

    $OverallResult = $XmlContent.REPORT.OVERALL_RESULT.Result
    $Color = if ($OverallResult -eq "PASS") { "Green" } else { "Red" }

    Write-Host "Overall Result: $OverallResult" -ForegroundColor $Color

    # List Failures if any
    if ($OverallResult -ne "PASS") {
        Write-Host "`nFailures:" -ForegroundColor Red
        $XmlContent.REPORT.REQUIREMENTS.REQUIREMENT | Where-Object { $_.OVERALL_RESULT.Result -eq "FAIL" } | ForEach-Object {
            Write-Host "  [-] $($_.Name)" -ForegroundColor Red
        }
    } else {
        Write-Host "All checks passed!" -ForegroundColor Green
    }
} else {
    # If report is missing, maybe WACK failed to start or crashed.
    # Check if a partial report or error log exists in the default WACK folder?
    # Usually valid reports are only generated on success/completion.

    Write-Error "Report file not found at: $ReportXml"
    Write-Host "Possible causes:" -ForegroundColor Yellow
    Write-Host "1. App installation failed (Check if the app is already installed with a different cert?)"
    Write-Host "2. WACK crashed or was interrupted."
}

Write-Host "`nPress Enter to close..." -ForegroundColor Gray
Read-Host
